listening-port=3478
tls-listening-port=5349
min-port=50000
max-port=50100

realm=auralis.local
fingerprint
lt-cred-mech
user=auralisuser:auralispassword

no-multicast-peers
no-cli
no-tls
no-dtls
log-file=stdout
